# Generated by Django 3.2.6 on 2021-08-12 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='signup',
        ),
    ]
