# Generated by Django 3.2.6 on 2021-08-16 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0005_auto_20210816_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(max_length=750),
        ),
    ]
