# Generated by Django 3.2.6 on 2021-08-20 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0009_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='productprice',
            field=models.PositiveIntegerField(max_length=20, null=True),
        ),
    ]
