# Generated by Django 3.2.6 on 2021-08-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0011_auto_20210825_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='ordered',
            field=models.BooleanField(default=False),
        ),
    ]
