# Generated by Django 3.2.6 on 2021-08-25 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0013_orders_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='items',
        ),
        migrations.RemoveField(
            model_name='orders',
            name='ordered',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
