# Generated by Django 3.2.6 on 2021-08-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0014_auto_20210825_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
