# Generated by Django 3.2.6 on 2021-08-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0016_auto_20210825_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carts',
            name='image',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
