# Generated by Django 3.2.6 on 2021-08-27 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0018_orders_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
