# Generated by Django 3.2.6 on 2021-08-28 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0022_auto_20210828_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='cart',
            field=models.ForeignKey(default='cfedefaultcart', on_delete=django.db.models.deletion.CASCADE, to='pharmaapp.carts'),
            preserve_default=False,
        ),
    ]
