# Generated by Django 3.2.6 on 2021-08-28 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0025_rename_cart_orders_cart_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='cart_id',
            new_name='cart',
        ),
    ]
