# Generated by Django 3.2.6 on 2021-08-30 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0026_rename_cart_id_orders_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='cart',
        ),
        migrations.DeleteModel(
            name='carts',
        ),
    ]
