# Generated by Django 3.2.6 on 2021-08-30 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pharmaapp', '0027_auto_20210830_2251'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='amount',
        ),
    ]
